title: aSSIsT Project
author: aSSIsT Project Members
email: some.mail@address.com
description: > # this means to ignore newlines until "baseurl:"
  aSSIsT Project

twitter_username: assist-project
github_username:  assist-project

sass:
    style: compressed
